version: '3'

services:
  web:
    build: ./docker
    container_name: web
    ports:
      - 80:80
    privileged: true
    volumes:
      - ./server:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      TZ: ${TIMEZONE}
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/dbsetting/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/log:/var/log/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_HOSTS=db
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_USER_PASSWORD}
    ports:
      - 3000:80